name: Build Release Pack

on:
  workflow_dispatch:
    inputs:
      package:
        description: "Escolha o pacote que deseja gerar o ZIP"
        required: true
        default: "Instalacao_completa"
        type: choice
        options:
          - Instalacao_completa
          - Mensageria
          - Outbound

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Configurar ambiente
        run: |
          echo "Rodando build para o pacote: ${{ github.event.inputs.package }}"

      - name: Run build
        env:
          PACKAGE: ${{ github.event.inputs.package }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          go run ./cmd/main.go

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: latest_releases_${{ github.event.inputs.package }}
          path: /tmp/latest_releases.zip
